{% set name = "ligo-asimov" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80f2cadf41df67016fd280ba59140b4a780fab8ebb065a4c3039ca222d8a3c6c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - locutus=asimov.locutus:cli
    - olivaw=asimov.olivaw:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - click
    - gitpython
    - ligo-gracedb
    - liquidpy
    - networkx
    - otter-report
    - python >=3.6
    - python-gitlab
    - python-htcondor
    - pytz
    - setuptools

test:
  requires:
    - pip
  imports:
    - asimov
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - locutus --help
    - olivaw --help

about:
  home: https://asimov.docs.ligo.org/asimov/
  doc_url: https://asimov.docs.ligo.org/asimov/
  dev_url: https://git.ligo.org/asimov/asimov.git
  license: ISC
  license_file: LICENSE
  summary: 'Parameter Estimation automator for gravitational wave analyses.'
  description: |
    asimov is a python package used to construct automated bots to do
    various things with parameter estimation jobs for gravitational
    wave data analysis.
    There are a number of bits of code which are designed to make
    writing your own bot easier, and these are importable, but there
    are also pre-baked bots.

extra:
  recipe-maintainers:
    - transientlunatic
    - duncanmmacleod
