{% set name = "ligo-asimov" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80f2cadf41df67016fd280ba59140b4a780fab8ebb065a4c3039ca222d8a3c6c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - locutus=asimov.locutus:cli
    - olivaw=asimov.olivaw:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - setuptools_scm

test:
  imports:
    - asimov
  commands:
    - locutus --help
    - olivaw --help

about:
  home: https://github.com/transientlunatic/asimov
  license: ISC
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'Parameter Estimation automator for gravitational wave analyses.'
  description: |
    asimov is a python package used to construct automated bots to do
    various things with parameter estimation jobs for gravitational
    wave data analysis.
    There are a number of bits of code which are designed to make
    writing your own bot easier, and these are importable, but there
    are also pre-baked bots.
  doc_url: https://daniel-williams.docs.ligo.org/supervisor/
  dev_url: https://github.com/transientlunatic/asimov

extra:
  recipe-maintainers:
    - transientlunatic
    - duncanmmacleod
