{% set name = "ligo-asimov" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3fb7bb3d45eb918897819d3a987854d3e37c46fd007d1f1962fe76320cd50d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - locutus=asimov.locutus:cli
    - olivaw=asimov.olivaw:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - click
    - gitpython
    - ligo-gracedb
    - liquidpy
    - networkx
    - otter-report
    - python >=3.6
    - python-gitlab
    - python-htcondor
    - pytz
    - setuptools

test:
  requires:
    - pip
  imports:
    - asimov
  commands:
    # check requirements
    - python -m pip check
    # check entry points
    - locutus --help
    - olivaw --help

about:
  home: https://github.com/transientlunatic/asimov
  license: ISC
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'Parameter Estimation automator for gravitational wave analyses.'
  description: |
    asimov is a python package used to construct automated bots to do
    various things with parameter estimation jobs for gravitational
    wave data analysis.
    There are a number of bits of code which are designed to make
    writing your own bot easier, and these are importable, but there
    are also pre-baked bots.
  doc_url: https://daniel-williams.docs.ligo.org/supervisor/
  dev_url: https://github.com/transientlunatic/asimov

extra:
  recipe-maintainers:
    - transientlunatic
    - duncanmmacleod
